// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygtmdrsrlyteuuvzwqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndG1kcnNybHl0ZXV1dnp3cWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTkyMDAsImV4cCI6MjA2MjU3NTIwMH0.Qx06tI65zz3TKEfLq3b9RO1LDcXTKh78CYChzYcLTxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);