
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration
const SUPABASE_URL = "https://ygtmdrsrlyteuuvzwqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndG1kcnNybHl0ZXV1dnp3cWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTkyMDAsImV4cCI6MjA2MjU3NTIwMH0.Qx06tI65zz3TKEfLq3b9RO1LDcXTKh78CYChzYcLTxY";

// Site URL configuration
const SITE_URL = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' 
  ? window.location.origin 
  : 'https://konverter.ai'; // Replace with your custom domain

// Create and export the Supabase client with site URL for auth redirects
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Configure redirects for authentication flows
      url: {
        redirectTo: `${SITE_URL}/auth/callback`,
      },
    },
  }
);

// You can import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
