
name: Deploy to Supabase Storage

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://github.com/supabase/cli/releases/download/v1.64.8/supabase_1.64.8_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          rm supabase.deb

      - name: Deploy to Supabase Storage
        env:
          SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlndG1kcnNybHl0ZXV1dnp3cWp2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Njk5OTIwMCwiZXhwIjoyMDYyNTc1MjAwfQ.YeFJT-MdGQvzB7OA4KET9JJN5wx9JDEuP45H3iS0iFg"
        run: |
          echo $SUPABASE_SERVICE_KEY | supabase login
          supabase link --project-ref ygtmdrsrlyteuuvzwqjv
          supabase storage create bucket website --public || true
          supabase storage update bucket website --public
          supabase storage upload website ./dist --recursive
